

// import React from 'react';
// import { Link, useNavigate } from 'react-router-dom';
// import { Button } from '../components/ui/button';
// import { ThemeToggle } from '../components/ThemeToggle';
// import { FeatureCard } from '../components/ui/feature-card';
// import { StatCard } from '../components/ui/stat-card';
// import { GlassCard } from '../components/ui/glass-card';
// import { Card } from '../components/ui/card';
// import Maya3D from '../components/Maya3D';
// import { ArrowRight, BookOpen, Users, Trophy, Sparkles, Globe, Zap, Star, Play } from 'lucide-react';

// const Landing = () => {
//   const navigate = useNavigate();

//   const features = [
//     {
//       icon: BookOpen,
//       title: 'AI-Powered Lessons',
//       description: 'Personalized English lessons generated by advanced AI technology',
//     },
//     {
//       icon: Users,
//       title: 'Multi-Language Support',
//       description: 'Learn English from German, Swahili, or enhance your existing skills',
//     },
//     {
//       icon: Trophy,
//       title: 'Gamified Learning',
//       description: 'Earn Integration Points, unlock achievements, and climb leaderboards',
//     },
//     {
//       icon: Sparkles,
//       title: '3D AI Tutor Maya',
//       description: 'Interactive 3D mascot provides guidance and encouragement',
//     },
//   ];

//   const stats = [
//     { number: '50K+', label: 'Active Learners' },
//     { number: '1M+', label: 'Lessons Completed' },
//     { number: '95%', label: 'Success Rate' },
//     { number: '30+', label: 'Countries' },
//   ];

//   return (
//     <div className="min-h-screen bg-gradient-surface grain relative">
//       {/* Hero Section */}
//       <section className="relative px-4 pt-12 pb-16 sm:pt-16 sm:pb-20">
//         <div className="max-w-7xl mx-auto">
//           {/* Navigation */}
//           <nav className="flex items-center justify-between mb-10 sm:mb-16">
//             <div className="flex items-center space-x-2 group">
//               <div className="w-8 h-8 bg-gradient-primary rounded-full flex items-center justify-center animate-glow-pulse group-hover:scale-110 transition-transform">
//                 <span className="text-sm font-bold text-primary-foreground">M</span>
//               </div>
//               <span className="text-lg sm:text-xl font-bold text-foreground group-hover:scale-105 transition-transform">
//                 MayaCode-Quest
//               </span>
//             </div>
//             <div className="flex items-center space-x-2 sm:space-x-4">
//               <ThemeToggle />
//               <Button variant="ghost" size="sm" asChild>
//                 <Link to="/app">Open App</Link>
//               </Button>
//               <Button variant="glossy" size="sm" asChild>
//                 <Link to="/app" className="flex items-center">
//                   Get Started <ArrowRight className="w-4 h-4 ml-1 sm:ml-2" />
//                 </Link>
//               </Button>
//             </div>
//           </nav>

//           {/* Hero Content */}
//           <div className="grid lg:grid-cols-2 gap-10 sm:gap-16 items-center">
//             {/* Text Section */}
//             <div className="space-y-6 sm:space-y-8 text-center lg:text-left">
//               <div className="space-y-4 sm:space-y-6">
//                 <div className="inline-flex items-center space-x-2 glass backdrop-blur-xl border border-white/20 rounded-full px-3 py-1.5 sm:px-4 sm:py-2">
//                   <Star className="w-4 h-4 text-warning" />
//                   <span className="text-xs sm:text-sm font-medium text-muted-foreground">
//                     #1 AI English Learning Platform
//                   </span>
//                 </div>

//                 <h1 className="text-3xl sm:text-5xl lg:text-6xl font-bold text-foreground leading-tight">
//                   Master UK English with{' '}
//                   <span className="bg-gradient-primary bg-clip-text text-transparent">
//                     AI Intelligence
//                   </span>
//                 </h1>

//                 <p className="text-base sm:text-lg lg:text-xl text-muted-foreground leading-relaxed max-w-lg mx-auto lg:mx-0">
//                   Join millions learning English with our revolutionary AI tutoring system.
//                   Personalized lessons, gamified experience, and real progress tracking.
//                 </p>
//               </div>

//               {/* Buttons */}
//               <div className="flex flex-col sm:flex-row gap-3 sm:gap-4 justify-center lg:justify-start">
//                 <Button
//                   variant="glossy"
//                   size="lg"
//                   className="w-full sm:w-auto"
//                   onClick={() => navigate('/app')}
//                 >
//                   <Play className="w-5 h-5 mr-2" />
//                   Start Learning Now
//                 </Button>
//                 <Button
//                   variant="premium"
//                   size="lg"
//                   asChild
//                   className="w-full sm:w-auto"
//                 >
//                   <Link to="/language-select">
//                     <Globe className="w-5 h-5 mr-2" />
//                     Choose Your Language
//                   </Link>
//                 </Button>
//               </div>

//               {/* Quick Stats */}
//               <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 pt-6 sm:pt-8">
//                 {stats.map((stat, index) => (
//                   <StatCard key={index} number={stat.number} label={stat.label} />
//                 ))}
//               </div>
//             </div>

//             {/* 3D Maya Showcase */}
//             <div className="flex justify-center lg:justify-end mt-10 lg:mt-0">
//               <div className="relative w-[280px] h-[280px] sm:w-[400px] sm:h-[400px] lg:w-[550px] lg:h-[550px]">
//                 <div className="absolute inset-0 bg-gradient-hero rounded-full blur-3xl opacity-20"></div>
//                 <Card className="relative p-2 sm:p-4 card-premium w-full h-full flex items-center justify-center">
//                   <Maya3D
//                     height="100%"
//                     showMessage={true}
//                     message="Hello! I'm Maya, your AI English tutor. Ready to start your learning journey?"
//                     className="w-full h-full"
//                   />
//                 </Card>
//                 <div className="absolute -bottom-4 left-1/2 transform -translate-x-1/2">
//                   <div className="bg-glass/80 backdrop-blur-sm rounded-full px-3 py-1 sm:px-4 sm:py-2 border border-glass-border animate-bounce-in">
//                     <span className="text-xs sm:text-sm font-medium text-glass-foreground">
//                       Maya is here to help!
//                     </span>
//                   </div>
//                 </div>
//               </div>
//             </div>
//           </div>
//         </div>
//       </section>

//       {/* Features Section */}
//       <section className="px-4 py-12 sm:py-20 bg-gradient-to-b from-transparent to-white/5">
//         <div className="max-w-7xl mx-auto">
//           <div className="text-center mb-10 sm:mb-16">
//             <h2 className="text-2xl sm:text-3xl lg:text-4xl font-bold text-foreground mb-3 sm:mb-4">
//               Why Choose MayaQuest?
//             </h2>
//             <p className="text-base sm:text-lg text-muted-foreground max-w-2xl mx-auto">
//               Advanced AI technology meets proven learning methods to deliver
//               the most effective English learning experience.
//             </p>
//           </div>

//           <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 sm:gap-8">
//             {features.map((feature, index) => {
//               const Icon = feature.icon;
//               return (
//                 <FeatureCard
//                   key={index}
//                   title={feature.title}
//                   description={feature.description}
//                   icon={<Icon className="w-6 h-6" />}
//                   variant="vibrant"
//                 />
//               );
//             })}
//           </div>
//         </div>
//       </section>

//       {/* CTA Section */}
//       <section className="px-4 py-12 sm:py-20">
//         <div className="max-w-4xl mx-auto text-center">
//           <GlassCard variant="vibrant" className="p-8 sm:p-12">
//             <div className="space-y-4 sm:space-y-6">
//               <div className="w-12 h-12 sm:w-16 sm:h-16 bg-gradient-primary rounded-full flex items-center justify-center mx-auto animate-glow-pulse">
//                 <Zap className="w-6 h-6 sm:w-8 sm:h-8 text-primary-foreground" />
//               </div>

//               <h2 className="text-2xl sm:text-3xl lg:text-4xl font-bold text-foreground">
//                 Ready to Master English?
//               </h2>

//               <p className="text-base sm:text-lg text-muted-foreground max-w-2xl mx-auto">
//                 Join thousands of learners who have already improved their English skills
//                 with MayaQuest's AI-powered lessons and gamified learning experience.
//               </p>

//               <div className="flex flex-col sm:flex-row gap-3 sm:gap-4 justify-center pt-4">
//                 <Button
//                   variant="glossy"
//                   size="lg"
//                   onClick={() => navigate('/app')}
//                   className="hover:scale-105 transition-transform w-full sm:w-auto"
//                 >
//                   <BookOpen className="w-5 h-5 mr-2" />
//                   Start Your Journey
//                 </Button>
//                 <Button
//                   variant="premium"
//                   size="lg"
//                   asChild
//                   className="hover:scale-105 transition-transform w-full sm:w-auto"
//                 >
//                   <Link to="/app">Learn More</Link>
//                 </Button>
//               </div>
//             </div>
//           </GlassCard>
//         </div>
//       </section>

//       {/* Footer */}
//       <footer className="px-4 py-8 sm:py-12 glass border-t border-white/20 backdrop-blur-xl">
//         <div className="max-w-7xl mx-auto">
//           <div className="flex flex-col md:flex-row items-center justify-between gap-4">
//             <div className="flex items-center space-x-2 group">
//               <div className="w-6 h-6 bg-gradient-primary rounded-full flex items-center justify-center group-hover:scale-110 transition-transform">
//                 <span className="text-xs font-bold text-primary-foreground">M</span>
//               </div>
//               <span className="font-semibold text-foreground group-hover:scale-105 transition-transform">
//                 MayaQuest
//               </span>
//             </div>

//             <div className="flex flex-col sm:flex-row items-center space-x-0 sm:space-x-6 text-xs sm:text-sm text-muted-foreground gap-2 sm:gap-0">
//               <span>© 2024 MayaQuest. All rights reserved.</span>
//               <Button variant="link" size="sm" asChild>
//                 <Link to="/app">Open App</Link>
//               </Button>
//             </div>
//           </div>
//         </div>
//       </footer>
//     </div>
//   );
// };

// export default Landing;




import React from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Button } from '../components/ui/button';
import { ThemeToggle } from '../components/ThemeToggle';
import { FeatureCard } from '../components/ui/feature-card';
import { StatCard } from '../components/ui/stat-card';
import { GlassCard } from '../components/ui/glass-card';
import { Card } from '../components/ui/card';
import Maya3D from '../components/Maya3D';
import { ArrowRight, BookOpen, Users, Trophy, Sparkles, Globe, Zap, Star, Play } from 'lucide-react';

const Landing = () => {
  const navigate = useNavigate();

  const features = [
    {
      icon: BookOpen,
      title: 'AI-Powered Lessons',
      description: 'Personalized English lessons generated by advanced AI technology',
    },
    {
      icon: Users,
      title: 'Multi-Language Support',
      description: 'Learn English from German, Swahili, or enhance your existing skills',
    },
    {
      icon: Trophy,
      title: 'Gamified Learning',
      description: 'Earn Integration Points, unlock achievements, and climb leaderboards',
    },
    {
      icon: Sparkles,
      title: '3D AI Tutor Maya',
      description: 'Interactive 3D mascot provides guidance and encouragement',
    },
  ];

  const stats = [
    { number: '50K+', label: 'Active Learners' },
    { number: '1M+', label: 'Lessons Completed' },
    { number: '95%', label: 'Success Rate' },
    { number: '30+', label: 'Countries' },
  ];

  return (
    <div className="min-h-screen bg-gradient-surface grain relative">
      {/* Hero Section */}
      <section className="relative px-4 pt-12 pb-16 sm:pt-16 sm:pb-20">
        <div className="max-w-7xl mx-auto">
          {/* Navigation */}
          <nav className="flex items-center justify-between mb-10 sm:mb-16">
            <div className="flex items-center space-x-2 group">
              <div className="w-8 h-8 bg-gradient-primary rounded-full flex items-center justify-center animate-glow-pulse group-hover:scale-110 transition-transform">
                <span className="text-sm font-bold text-primary-foreground">M</span>
              </div>
              <span className="text-lg sm:text-xl font-bold text-foreground group-hover:scale-105 transition-transform">
                MayaQuest
              </span>
            </div>
            <div className="flex items-center space-x-2 sm:space-x-4">
              <ThemeToggle />
              <Button variant="ghost" size="sm" asChild>
                <Link to="/app">Open App</Link>
              </Button>
              {/* Hidden on mobile, visible on sm+ */}
              <Button variant="glossy" size="sm" asChild className="hidden sm:flex">
                <Link to="/app" className="flex items-center">
                  Get Started <ArrowRight className="w-4 h-4 ml-1 sm:ml-2" />
                </Link>
              </Button>
            </div>
          </nav>

          {/* Hero Content */}
          <div className="grid lg:grid-cols-2 gap-10 sm:gap-16 items-center">
            {/* Text Section */}
            <div className="space-y-6 sm:space-y-8 text-center lg:text-left">
              <div className="space-y-4 sm:space-y-6">
                <div className="inline-flex items-center space-x-2 glass backdrop-blur-xl border border-white/20 rounded-full px-3 py-1.5 sm:px-4 sm:py-2">
                  <Star className="w-4 h-4 text-warning" />
                  <span className="text-xs sm:text-sm font-medium text-muted-foreground">
                    #1 AI English Learning Platform
                  </span>
                </div>

                <h1 className="text-3xl sm:text-5xl lg:text-6xl font-bold text-foreground leading-tight">
                  Master UK English with{' '}
                  <span className="bg-gradient-primary bg-clip-text text-transparent">
                    AI Intelligence
                  </span>
                </h1>

                <p className="text-base sm:text-lg lg:text-xl text-muted-foreground leading-relaxed max-w-lg mx-auto lg:mx-0">
                  Join millions learning English with our revolutionary AI tutoring system.
                  Personalized lessons, gamified experience, and real progress tracking.
                </p>
              </div>

              {/* Buttons */}
              <div className="flex flex-col sm:flex-row gap-3 sm:gap-4 justify-center lg:justify-start">
                <Button
                  variant="glossy"
                  size="lg"
                  className="w-full sm:w-auto"
                  onClick={() => navigate('/app')}
                >
                  <Play className="w-5 h-5 mr-2" />
                  Start Learning Free
                </Button>
                <Button
                  variant="premium"
                  size="lg"
                  asChild
                  className="w-full sm:w-auto"
                >
                  <Link to="/language-select">
                    <Globe className="w-5 h-5 mr-2" />
                    Choose Your Language
                  </Link>
                </Button>
              </div>

              {/* Quick Stats */}
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 pt-6 sm:pt-8">
                {stats.map((stat, index) => (
                  <StatCard key={index} number={stat.number} label={stat.label} />
                ))}
              </div>
            </div>

            {/* 3D Maya Showcase */}
            <div className="flex justify-center lg:justify-end mt-10 lg:mt-0">
              <div className="relative w-[280px] h-[280px] sm:w-[400px] sm:h-[400px] lg:w-[550px] lg:h-[550px]">
                <div className="absolute inset-0 bg-gradient-hero rounded-full blur-3xl opacity-20"></div>
                <Card className="relative p-2 sm:p-4 card-premium w-full h-full flex items-center justify-center">
                  <Maya3D
                    height="100%"
                    showMessage={true}
                    message="Hello! I'm Maya, your AI English tutor. Ready to start your learning journey?"
                    className="w-full h-full"
                  />
                </Card>
                <div className="absolute -bottom-4 left-1/2 transform -translate-x-1/2">
                  <div className="bg-glass/80 backdrop-blur-sm rounded-full px-3 py-1 sm:px-4 sm:py-2 border border-glass-border animate-bounce-in">
                    <span className="text-xs sm:text-sm font-medium text-glass-foreground">
                      Maya is here to help!
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="px-4 py-12 sm:py-20 bg-gradient-to-b from-transparent to-white/5">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-10 sm:mb-16">
            <h2 className="text-2xl sm:text-3xl lg:text-4xl font-bold text-foreground mb-3 sm:mb-4">
              Why Choose MayaQuest?
            </h2>
            <p className="text-base sm:text-lg text-muted-foreground max-w-2xl mx-auto">
              Advanced AI technology meets proven learning methods to deliver
              the most effective English learning experience.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 sm:gap-8">
            {features.map((feature, index) => {
              const Icon = feature.icon;
              return (
                <FeatureCard
                  key={index}
                  title={feature.title}
                  description={feature.description}
                  icon={<Icon className="w-6 h-6" />}
                  variant="vibrant"
                />
              );
            })}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="px-4 py-12 sm:py-20">
        <div className="max-w-4xl mx-auto text-center">
          <GlassCard variant="vibrant" className="p-8 sm:p-12">
            <div className="space-y-4 sm:space-y-6">
              <div className="w-12 h-12 sm:w-16 sm:h-16 bg-gradient-primary rounded-full flex items-center justify-center mx-auto animate-glow-pulse">
                <Zap className="w-6 h-6 sm:w-8 sm:h-8 text-primary-foreground" />
              </div>

              <h2 className="text-2xl sm:text-3xl lg:text-4xl font-bold text-foreground">
                Ready to Master English?
              </h2>

              <p className="text-base sm:text-lg text-muted-foreground max-w-2xl mx-auto">
                Join thousands of learners who have already improved their English skills
                with MayaQuest's AI-powered lessons and gamified learning experience.
              </p>

              <div className="flex flex-col sm:flex-row gap-3 sm:gap-4 justify-center pt-4">
                <Button
                  variant="glossy"
                  size="lg"
                  onClick={() => navigate('/app')}
                  className="hover:scale-105 transition-transform w-full sm:w-auto"
                >
                  <BookOpen className="w-5 h-5 mr-2" />
                  Start Your Journey
                </Button>
                <Button
                  variant="premium"
                  size="lg"
                  asChild
                  className="hover:scale-105 transition-transform w-full sm:w-auto"
                >
                  <Link to="/app">Learn More</Link>
                </Button>
              </div>
            </div>
          </GlassCard>
        </div>
      </section>

      {/* Footer */}
      <footer className="px-4 py-8 sm:py-12 glass border-t border-white/20 backdrop-blur-xl">
        <div className="max-w-7xl mx-auto">
          <div className="flex flex-col md:flex-row items-center justify-between gap-4">
            <div className="flex items-center space-x-2 group">
              <div className="w-6 h-6 bg-gradient-primary rounded-full flex items-center justify-center group-hover:scale-110 transition-transform">
                <span className="text-xs font-bold text-primary-foreground">M</span>
              </div>
              <span className="font-semibold text-foreground group-hover:scale-105 transition-transform">
                MayaQuest
              </span>
            </div>

            <div className="flex flex-col sm:flex-row items-center space-x-0 sm:space-x-6 text-xs sm:text-sm text-muted-foreground gap-2 sm:gap-0">
              <span>© 2024 MayaQuest. All rights reserved.</span>
              <Button variant="link" size="sm" asChild>
                <Link to="/app">Open App</Link>
              </Button>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default Landing;
