import React from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Button } from '../components/ui/button';
import { ThemeToggle } from '../components/ThemeToggle';
import { FeatureCard } from '../components/ui/feature-card';
import { StatCard } from '../components/ui/stat-card';
import { MayaContainer } from '../components/ui/maya-container';
import { GlassCard } from '../components/ui/glass-card';
import { ArrowRight, BookOpen, Users, Trophy, Sparkles, Globe, Zap, Star, Play } from 'lucide-react';

const Landing = () => {
  const navigate = useNavigate();

  const features = [
    {
      icon: BookOpen,
      title: 'AI-Powered Lessons',
      description: 'Personalized English lessons generated by advanced AI technology',
    },
    {
      icon: Users,
      title: 'Multi-Language Support',
      description: 'Learn English from German, Swahili, or enhance your existing skills',
    },
    {
      icon: Trophy,
      title: 'Gamified Learning',
      description: 'Earn Integration Points, unlock achievements, and climb leaderboards',
    },
    {
      icon: Sparkles,
      title: '3D AI Tutor Maya',
      description: 'Interactive 3D mascot provides guidance and encouragement',
    },
  ];

  const stats = [
    { number: '50K+', label: 'Active Learners' },
    { number: '1M+', label: 'Lessons Completed' },
    { number: '95%', label: 'Success Rate' },
    { number: '30+', label: 'Countries' },
  ];

  return (
    <div className="min-h-screen bg-gradient-surface grain relative">
      {/* Hero Section */}
      <section className="relative px-4 pt-16 pb-20">
        <div className="max-w-7xl mx-auto">
          {/* Navigation */}
          <nav className="flex items-center justify-between mb-16">
            <div className="flex items-center space-x-2 group">
              <div className="w-8 h-8 bg-gradient-primary rounded-full flex items-center justify-center animate-glow-pulse group-hover:scale-110 transition-transform">
                <span className="text-sm font-bold text-primary-foreground">M</span>
              </div>
              <span className="text-xl font-bold text-foreground group-hover:scale-105 transition-transform">MayaQuest</span>
            </div>
            <div className="flex items-center space-x-4">
              <ThemeToggle />
              <Button variant="ghost" asChild>
                <Link to="/app">Open App</Link>
              </Button>
              <Button variant="glossy" asChild>
                <Link to="/app">
                  Get Started <ArrowRight className="w-4 h-4 ml-2" />
                </Link>
              </Button>
            </div>
          </nav>

          {/* Hero Content */}
          <div className="grid lg:grid-cols-2 gap-16 items-center">
            <div className="space-y-8">
              <div className="space-y-6">
                <div className="inline-flex items-center space-x-2 glass backdrop-blur-xl border border-white/20 rounded-full px-4 py-2">
                  <Star className="w-4 h-4 text-warning" />
                  <span className="text-sm font-medium text-muted-foreground">
                    #1 AI English Learning Platform
                  </span>
                </div>
                
                <h1 className="text-5xl lg:text-6xl font-bold text-foreground leading-tight">
                  Master UK English with{' '}
                  <span className="bg-gradient-primary bg-clip-text text-transparent">
                    AI Intelligence
                  </span>
                </h1>
                
                <p className="text-xl text-muted-foreground leading-relaxed max-w-lg">
                  Join millions learning English with our revolutionary AI tutoring system. 
                  Personalized lessons, gamified experience, and real progress tracking.
                </p>
              </div>

              <div className="flex flex-col sm:flex-row gap-4">
                <Button variant="glossy" size="lg" onClick={() => navigate('/app')}>
                  <Play className="w-5 h-5 mr-2" />
                  Start Learning Free
                </Button>
                <Button variant="premium" size="lg" asChild>
                  <Link to="/app">
                    <Globe className="w-5 h-5 mr-2" />
                    Choose Your Language
                  </Link>
                </Button>
              </div>

              {/* Quick Stats */}
              <div className="grid grid-cols-4 gap-4 pt-8">
                {stats.map((stat, index) => (
                  <StatCard 
                    key={index}
                    number={stat.number}
                    label={stat.label}
                  />
                ))}
              </div>
            </div>

            {/* 3D Maya Showcase */}
            <div className="flex justify-center lg:justify-end">
              <MayaContainer
                variant="hero"
                height="400px"
                showMessage={true}
                message="Hello! I'm Maya"
                className="animate-float"
              />
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="px-4 py-20 bg-gradient-to-b from-transparent to-white/5">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-3xl lg:text-4xl font-bold text-foreground mb-4">
              Why Choose MayaQuest?
            </h2>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              Advanced AI technology meets proven learning methods to deliver 
              the most effective English learning experience.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {features.map((feature, index) => {
              const Icon = feature.icon;
              return (
                <FeatureCard
                  key={index}
                  title={feature.title}
                  description={feature.description}
                  icon={<Icon className="w-6 h-6" />}
                  variant="vibrant"
                />
              );
            })}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="px-4 py-20">
        <div className="max-w-4xl mx-auto text-center">
          <GlassCard variant="vibrant" className="p-12">
            <div className="space-y-6">
              <div className="w-16 h-16 bg-gradient-primary rounded-full flex items-center justify-center mx-auto animate-glow-pulse">
                <Zap className="w-8 h-8 text-primary-foreground" />
              </div>
              
              <h2 className="text-3xl lg:text-4xl font-bold text-foreground">
                Ready to Master English?
              </h2>
              
              <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
                Join thousands of learners who have already improved their English skills 
                with MayaQuest's AI-powered lessons and gamified learning experience.
              </p>
              
              <div className="flex flex-col sm:flex-row gap-4 justify-center pt-4">
                <Button variant="glossy" size="xl" onClick={() => navigate('/app')} className="hover:scale-105 transition-transform">
                  <BookOpen className="w-5 h-5 mr-2" />
                  Start Your Journey
                </Button>
                <Button variant="premium" size="xl" asChild className="hover:scale-105 transition-transform">
                  <Link to="/app">
                    Learn More
                  </Link>
                </Button>
              </div>
            </div>
          </GlassCard>
        </div>
      </section>

      {/* Footer */}
      <footer className="px-4 py-12 glass border-t border-white/20 backdrop-blur-xl">
        <div className="max-w-7xl mx-auto">
          <div className="flex flex-col md:flex-row items-center justify-between">
            <div className="flex items-center space-x-2 mb-4 md:mb-0 group">
              <div className="w-6 h-6 bg-gradient-primary rounded-full flex items-center justify-center group-hover:scale-110 transition-transform">
                <span className="text-xs font-bold text-primary-foreground">M</span>
              </div>
              <span className="font-semibold text-foreground group-hover:scale-105 transition-transform">MayaQuest</span>
            </div>
            
            <div className="flex items-center space-x-6 text-sm text-muted-foreground">
              <span>© 2024 MayaQuest. All rights reserved.</span>
              <Button variant="link" size="sm" asChild>
                <Link to="/app">Open App</Link>
              </Button>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default Landing;