import React from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { ThemeToggle } from '@/components/ThemeToggle';
import Maya3D from '@/components/Maya3D';
import { ArrowRight, BookOpen, Users, Trophy, Sparkles, Globe, Zap, Star, Play } from 'lucide-react';

const Landing = () => {
  const navigate = useNavigate();

  const features = [
    {
      icon: BookOpen,
      title: 'AI-Powered Lessons',
      description: 'Personalized English lessons generated by advanced AI technology',
    },
    {
      icon: Users,
      title: 'Multi-Language Support',
      description: 'Learn English from German, Swahili, or enhance your existing skills',
    },
    {
      icon: Trophy,
      title: 'Gamified Learning',
      description: 'Earn Integration Points, unlock achievements, and climb leaderboards',
    },
    {
      icon: Sparkles,
      title: '3D AI Tutor Maya',
      description: 'Interactive 3D mascot provides guidance and encouragement',
    },
  ];

  const stats = [
    { number: '50K+', label: 'Active Learners' },
    { number: '1M+', label: 'Lessons Completed' },
    { number: '95%', label: 'Success Rate' },
    { number: '30+', label: 'Countries' },
  ];

  return (
    <div className="min-h-screen bg-background grain relative">
      {/* Hero Section */}
      <section className="relative px-4 pt-16 pb-20">
        <div className="max-w-7xl mx-auto">
          {/* Navigation */}
          <nav className="flex items-center justify-between mb-16">
            <div className="flex items-center space-x-2">
              <div className="w-8 h-8 bg-gradient-primary rounded-full flex items-center justify-center">
                <span className="text-sm font-bold text-primary-foreground">M</span>
              </div>
              <span className="text-xl font-bold text-foreground">MayaQuest</span>
            </div>
            <div className="flex items-center space-x-4">
              <ThemeToggle />
              <Button variant="ghost" asChild>
                <Link to="/app">Open App</Link>
              </Button>
              <Button variant="glossy" asChild>
                <Link to="/app">
                  Get Started <ArrowRight className="w-4 h-4 ml-2" />
                </Link>
              </Button>
            </div>
          </nav>

          {/* Hero Content */}
          <div className="grid lg:grid-cols-2 gap-16 items-center">
            <div className="space-y-8">
              <div className="space-y-6">
                <div className="inline-flex items-center space-x-2 bg-surface-elevated border border-surface-border rounded-full px-4 py-2">
                  <Star className="w-4 h-4 text-warning" />
                  <span className="text-sm font-medium text-muted-foreground">
                    #1 AI English Learning Platform
                  </span>
                </div>
                
                <h1 className="text-5xl lg:text-6xl font-bold text-foreground leading-tight">
                  Master UK English with{' '}
                  <span className="bg-gradient-primary bg-clip-text text-transparent">
                    AI Intelligence
                  </span>
                </h1>
                
                <p className="text-xl text-muted-foreground leading-relaxed max-w-lg">
                  Join millions learning English with our revolutionary AI tutoring system. 
                  Personalized lessons, gamified experience, and real progress tracking.
                </p>
              </div>

              <div className="flex flex-col sm:flex-row gap-4">
                <Button variant="glossy" size="lg" onClick={() => navigate('/app')}>
                  <Play className="w-5 h-5 mr-2" />
                  Start Learning Free
                </Button>
                <Button variant="premium" size="lg" asChild>
                  <Link to="/app">
                    <Globe className="w-5 h-5 mr-2" />
                    Choose Your Language
                  </Link>
                </Button>
              </div>

              {/* Quick Stats */}
              <div className="grid grid-cols-4 gap-4 pt-8">
                {stats.map((stat, index) => (
                  <div key={index} className="text-center">
                    <div className="text-2xl font-bold text-foreground">{stat.number}</div>
                    <div className="text-sm text-muted-foreground">{stat.label}</div>
                  </div>
                ))}
              </div>
            </div>

            {/* 3D Maya Showcase */}
            <div className="flex justify-center lg:justify-end">
              <div className="relative">
                <div className="absolute inset-0 bg-gradient-hero rounded-full blur-3xl opacity-20"></div>
                <Card className="relative p-8 card-premium">
                  <Maya3D 
                    height="400px" 
                    showMessage={true}
                    message="Hello! I'm Maya, your AI English tutor. Ready to start your learning journey?"
                    className="animate-float"
                  />
                </Card>
                <div className="absolute -bottom-4 left-1/2 transform -translate-x-1/2">
                  <div className="bg-surface-elevated border border-surface-border rounded-full px-4 py-2 shadow-md">
                    <span className="text-sm font-medium text-foreground">
                      Maya - Your AI Learning Companion
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="px-4 py-20 bg-surface">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-3xl lg:text-4xl font-bold text-foreground mb-4">
              Why Choose MayaQuest?
            </h2>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              Advanced AI technology meets proven learning methods to deliver 
              the most effective English learning experience.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {features.map((feature, index) => {
              const Icon = feature.icon;
              return (
                <Card key={index} className="p-8 card-premium hover:shadow-lg transition-all duration-200">
                  <div className="flex items-start space-x-4">
                    <div className="w-12 h-12 bg-gradient-primary rounded-lg flex items-center justify-center flex-shrink-0">
                      <Icon className="w-6 h-6 text-primary-foreground" />
                    </div>
                    <div>
                      <h3 className="text-xl font-semibold text-foreground mb-2">
                        {feature.title}
                      </h3>
                      <p className="text-muted-foreground">
                        {feature.description}
                      </p>
                    </div>
                  </div>
                </Card>
              );
            })}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="px-4 py-20">
        <div className="max-w-4xl mx-auto text-center">
          <Card className="p-12 card-premium">
            <div className="space-y-6">
              <div className="w-16 h-16 bg-gradient-primary rounded-full flex items-center justify-center mx-auto">
                <Zap className="w-8 h-8 text-primary-foreground" />
              </div>
              
              <h2 className="text-3xl lg:text-4xl font-bold text-foreground">
                Ready to Master English?
              </h2>
              
              <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
                Join thousands of learners who have already improved their English skills 
                with MayaQuest's AI-powered lessons and gamified learning experience.
              </p>
              
              <div className="flex flex-col sm:flex-row gap-4 justify-center pt-4">
                <Button variant="glossy" size="xl" onClick={() => navigate('/app')}>
                  <BookOpen className="w-5 h-5 mr-2" />
                  Start Your Journey
                </Button>
                <Button variant="premium" size="xl" asChild>
                  <Link to="/app">
                    Learn More
                  </Link>
                </Button>
              </div>
            </div>
          </Card>
        </div>
      </section>

      {/* Footer */}
      <footer className="px-4 py-12 bg-surface border-t border-surface-border">
        <div className="max-w-7xl mx-auto">
          <div className="flex flex-col md:flex-row items-center justify-between">
            <div className="flex items-center space-x-2 mb-4 md:mb-0">
              <div className="w-6 h-6 bg-gradient-primary rounded-full flex items-center justify-center">
                <span className="text-xs font-bold text-primary-foreground">M</span>
              </div>
              <span className="font-semibold text-foreground">MayaQuest</span>
            </div>
            
            <div className="flex items-center space-x-6 text-sm text-muted-foreground">
              <span>© 2024 MayaQuest. All rights reserved.</span>
              <Button variant="link" size="sm" asChild>
                <Link to="/app">Open App</Link>
              </Button>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default Landing;