// Mock data for the redesigned MayaCode-Quest interface

// Data for global state store
export const mockStore = {
  theme: 'light' as const,
  user: {
    points: 1250,
    level: 5,
    streak: 7,
    nativeLanguage: 'de' as const,
    targetLanguage: 'en' as const,
  },
  progress: {
    dailyGoal: 50,
    todayProgress: 35,
    levelProgress: 75,
    pointsForNextLevel: 250,
  }
};

// Data returned by API queries
export const mockQuery = {
  userStats: {
    totalLearners: '50K+',
    lessonsCompleted: '1M+',
    successRate: '95%',
    countries: '30+',
  },
  features: [
    {
      id: 'ai-lessons',
      title: 'AI-Powered Lessons',
      description: 'Personalized English lessons generated by advanced AI technology',
      icon: 'BookOpen',
    },
    {
      id: 'multi-language',
      title: 'Multi-Language Support', 
      description: 'Learn English from German, Swahili, or enhance your existing skills',
      icon: 'Users',
    },
    {
      id: 'gamification',
      title: 'Gamified Learning',
      description: 'Earn Integration Points, unlock achievements, and climb leaderboards',
      icon: 'Trophy',
    },
    {
      id: 'maya-tutor',
      title: '3D AI Tutor Maya',
      description: 'Interactive 3D mascot provides guidance and encouragement',
      icon: 'Sparkles',
    },
  ],
};

// Data passed as props to the root component
export const mockRootProps = {
  currentRoute: '/',
  userProgress: {
    points: 1250,
    level: 5,
    streak: 7,
  },
  theme: 'light' as const,
  onThemeToggle: () => {},
  onNavigateToApp: () => {},
};